### ISSUE TITLE
Please build this, I would like to use this.

### ISSUE THREAD

**Issue by ninapavlich** [mattharley/django-backup-monster#8]
Please build this, I would like to use this! :D

I saw you have a TODO to add database backups. I have some code for this written -- feel free to copy/paste/improve/etc:

Database Backup Command: https://github.com/ninapavlich/django-carbon/blob/master/carbon/atoms/management/commands/backup_database.py
Database Backup Functions: https://github.com/ninapavlich/django-carbon/tree/master/carbon/utils/data

**Comment by mattharley** [comment]
thanks for the code examples! we are still a little while away from needing this as most of our data lives on Heroku Postgres databases - which have automated backups. we are thinking of eventually moving to pure AWS where i think this would come in handy!

**Comment by ninapavlich** [comment]
Makes sense! Good luck on the project!
